


logging:
  level:
    ROOT: ERROR
    diy.mqml: INFO
    org.springframework.security: DEBUG

spring:
  application:
    name: spring-boot-data

  h2:
    console:
      enabled: true
      path: /h2-console # Optional: Set the path for the H2 console - http://localhost:8080/h2-console

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



  #  jpa:
  #    hibernate:
  #      ddl-auto: validate


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
