
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    com.nimbusds: TRACE
    org.springframework.web.client.RestTemplate: DEBUG

spring:
#  application:
#    name: "backend"
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console # Optional: Set the path for the H2 console - http://localhost:8080/h2-console
#
#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml
#    enabled: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/a25fff9c-3f63-4fb2-9a8a-d9bdd0321f9a/v2.0
          audiences:
            - api://6b4f8dcc-e7d3-4d30-ab85-20851dca2013
            - 6b4f8dcc-e7d3-4d30-ab85-20851dca2013

  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: a25fff9c-3f63-4fb2-9a8a-d9bdd0321f9a
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        app-id-uri: 6b4f8dcc-e7d3-4d30-ab85-20851dca2013
#        authorization-clients:
#          graph:
#            scopes:
#              - https://graph.microsoft.com/User.Read
#              - https://graph.microsoft.com/User.Read.All
#              - https://graph.microsoft.com/profile
#              - https://graph.microsoft.com/Group.Read.All
